### ISSUE TITLE
Optimisation du processus d'inscription

### ISSUE THREAD

**Issue by Zabat** [ongolaboy/dacgl_utils#1]
Il est préférable de généré un lien sur le dernier inscrit qui apparaît sur le tableau de bord juste après l'enregistrement en vue de consigner sa présence, aulieu de le rechercher encore pour consigner sa présence.

**Comment by ongolaboy** [comment]
Corrigé dans le commit #e47c4ef2c37d6f48e3f8c4c50a88df03ab60b33e  :)
